import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class WindowNetBean extends JFrame {

    public WindowNetBean() {
        String[] students=new String[]{"Ivanov","Petrov","Sidorov","John"};
        String[] grades=new String[]{"5","4","3","2"};
        Object[][] tableContent= new Object [][] {
                {1,students[0],  null, null, null, null, null, null, null, null, null},
                {2,students[1],  null, null, null, null, null, null, null, null, null},
                {3,students[2],  null, null, null, null, null, null, null, null, null},
                {4,students[3],  null, null, null, null, null, null, null, null, null}
        };

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbStudents = new javax.swing.JComboBox<>(students);
        jLabel2 = new javax.swing.JLabel();
        cbGrades = new javax.swing.JComboBox<>(grades);
        jButton1.setText("Добавить оценку");

        initComponents(tableContent);

        jButton1.addActionListener(e -> {
            addGradeToStudent(cbStudents.getSelectedIndex(), cbGrades.getSelectedItem().toString());
        });

    }

    private void addGradeToStudent(int studentIndex, String grade) {
        int indexOfnewGrade=0;
        for (int i=2;i<10;i++){
            if (model.getValueAt(studentIndex,i)==null){
                indexOfnewGrade=i;
                break;
            } else if(i==9){
                JOptionPane.showMessageDialog(this,"Оценок уже 8!");
                return;
            }
        }
        model.setValueAt(grade,studentIndex,indexOfnewGrade);
        double countOfGrades=indexOfnewGrade-1;
        double averageGrade;
        double sumOfGrades=0;
        for (int i=2;i<=indexOfnewGrade;i++){

            sumOfGrades+=Double.parseDouble(model.getValueAt(studentIndex,i).toString())  ;
            System.out.println(sumOfGrades);
        }
        averageGrade=sumOfGrades/countOfGrades;
        model.setValueAt(averageGrade,studentIndex,10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Object[][] tableContent) {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Студент");

        model=new javax.swing.table.DefaultTableModel(tableContent,
                new String [] {
                        "№ п/п", "ФИО студента", "1", "2", "3", "4", "5", "6", "7", "8", "Итого"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };

        jTable1.setModel(model);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(60);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(1).setMinWidth(150);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(150);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(10).setMinWidth(40);
            jTable1.getColumnModel().getColumn(10).setMaxWidth(40);
        }

        jLabel2.setText("Оценка");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbGrades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton1)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(cbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(cbGrades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setVisible(true);
        setResizable(false);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> cbGrades;
    private javax.swing.JComboBox<String> cbStudents;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private DefaultTableModel model;
    // End of variables declaration 
    
}
